
services:
- docker

script:
- make all

before_deploy:
- make deploy
- cat .release-notes/template.md | envsubst > .release-notes/tmp-notes-${TRAVIS_TAG}.md

# From https://github.com/travis-ci/travis-ci/issues/7780#issuecomment-302389370
# we have to duplicate to meet tags and master
deploy:
  - provider: pages
    local-dir: ./docs/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    target-branch: gh-pages
    verbose: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != ^gh-pages$
  - provider: pages
    local-dir: ./docs/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    target-branch: gh-pages
    verbose: true
    on:
      tags: true
  - provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    skip_cleanup: true
    name: $TRAVIS_TAG
    edge: true
    release_notes_file: ".release-notes/tmp-notes-${TRAVIS_TAG}.md"
    on:
      tags: true
