version: '3'
services:
  reverseproxy:
    image: traefik:v2.0
    command:
      # enable docker
      # enable log
      # enable dashboard (insecure)
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./traefik.yml:/traefik.yml
#      - ../pebble/pebble.minica.pem:/pebble.minica.pem
#    environment:
#      - LEGO_CA_CERTIFICATES=/pebble.minica.pem
#      - LEGO_CA_SERVER_NAME=pebble

#  demo1:
#    image: juliens/webapp
#    environment:
#      - APPNAME=DEMO1



networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.51.0/24
