version: '3'
services:
  rproxy:
    image: traefik:v2.0.1
    command:
    - --api
    - --api.insecure
    - --providers.docker
    - --entrypoints.mongo.address=:27017
    ports:
      - "27017:27017"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:4.0
    hostname: mongo1.local
    labels:
      - "traefik.tcp.routers.mongo.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mongo.entrypoints=mongo"
