version: '3'
services:
  reverseproxy:
    image: traefik:v2.0
    command:
      - --providers.docker
      - --log.level=DEBUG
      - --api.insecure=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ossnet:

  demo1:
    image: juliens/webapp
    environment:
      - APPNAME=DEMO1
    networks:
      ossnet:

  demo2:
    image: juliens/webapp
    environment:
      - APPNAME=DEMO2
    labels:
      - traefik.http.routers.demo2.rule=Host(`myapp.com`)
    networks:
      ossnet:


networks:
  ossnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.50.0/24
