bootstrap:
  timeout: 600

image:
  name: store/containous/traefikee
  tag: v1.0.0
  pullPolicy: Always

# replicas:
#   dataNode:
#     total: 2

dashboard:
  type: ingress
  host: dashboard.docker.localhost

