version: '3'

services:
  rproxy:
    image: traefik:v2.0.2
    command:
      - --api
      - --api.insecure
      - --providers.docker
      - --providers.file.filename=/certs/traefik-tls.toml
      - --entrypoints.mongo.address=:27017
    ports:
      - "8080:8080"
      - "27017:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../certs:/certs

  mongo1:
    image: mongo:4.0
    hostname: mongo1.local
    restart: always
    labels:
      - "traefik.tcp.routers.mongo1.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mongo1.tls=true"
      - "traefik.tcp.routers.mongo1.entrypoints=mongo"
