---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-v2
  namespace: webapp
  labels:
    app: webapp-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-v2
  template:
    metadata:
      labels:
        app: webapp-v2
    spec:
      containers:
        - name: webapp-v2
          image: nginx:alpine
          ports:
            - name: web
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-v2
  namespace: webapp
  labels:
    app: webapp-v2
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: webapp-v2
